
server:
  port: 9090

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: base
    password: 123456

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.OracleDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: levantrang4302@gmail.com
    password: ggkpgtvjlxyvxhsq
    properties:
      mail:
        smtp:
          auth: true

          starttls:
            enable: true


application:
  security:
    jwt:
      secretKey: de6aaeabadeccc598160172044da9c566242ae3b
      tokenValidityMilliseconds: 86400000
      rememberMeTokenValiditySeconds: 25920000000
